name: Build, Test and Publish release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x.x
          
      
    - name: install workloads
      run: dotnet workload restore src/Avalonia.FuncUI.sln
      
    - name: Build & Test
      run: dotnet test src/Avalonia.FuncUI.sln --verbosity normal

    - name: Build Templates
      run: pushd ./src/Avalonia.FuncUI.Templates && chmod +x ./test-templates.ps1 && pwsh ./test-templates.ps1 && popd
      
    - name: Build for release
      run: dotnet build src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj -c Release
      
    - name: Build for release
      run: dotnet build src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj -c Release
      
    - name: Publish base project and Elmish NuGets (if this version was not published before)
      run: dotnet nuget push src/**/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
    
